In [4]:
import os
import random
import numpy as np
import librosa.display
import soundfile as sf
import csv

In [5]:
def get_files_count(folder_path):
	dirListing = os.listdir(folder_path)
	return len(dirListing)

In [6]:
PATH = "/Users/valleotb/Desktop/Valleotb/librispeech_no_process"
FILE_COUNT = get_files_count(PATH)
f = open('/Users/valleotb/Desktop/Valleotb/librispeech_metadata/metadata.csv','w', newline='')
wr = csv.writer(f)
wr.writerow(['slice_file_name','start','end'])

j = 100000
z = 200000
for i in range(FILE_COUNT):
    # dataload
    j += 1
    WAVEFORM, SR = sf.read(f"/Users/valleotb/Desktop/Valleotb/librispeech_no_process/{j}.flac")
    WAVEFORM = librosa.util.normalize(WAVEFORM)

    NON_SILENT_TIME = librosa.effects.split(WAVEFORM, top_db=20)
    print(NON_SILENT_TIME)

    if len(NON_SILENT_TIME) > 1 :
        for k in NON_SILENT_TIME :
            if (k[1] - k[0]) > 3000 :
                z += 1

                WAVEFORM, SR = sf.read(f"/Users/valleotb/Desktop/Valleotb/librispeech_no_process/{j}.flac")
                WAVEFORM = librosa.util.normalize(WAVEFORM)

                print(k[0],k[1])
                N_STEPS = random.randint(1,5)
                WAVEFORM_TRANSFORM = librosa.effects.pitch_shift(WAVEFORM[k[0]:k[1]], sr=SR, n_steps=N_STEPS)
                WAVEFORM_TRANSFORM_MINUS = librosa.effects.pitch_shift(WAVEFORM_TRANSFORM, sr=SR, n_steps=-N_STEPS)
                print("--")
                # Normalize
                WAVEFORM_NOT_TRANSFORM_PART = WAVEFORM[k[0]:k[1]]
                WAVEFORM_DOUBLED = WAVEFORM_NOT_TRANSFORM_PART ** 2
                WAVEFORM_TRANSFORM_DOUBLED = WAVEFORM_TRANSFORM_MINUS ** 2
                a = np.sqrt((WAVEFORM_DOUBLED.sum()) / (WAVEFORM_TRANSFORM_DOUBLED.sum()))

                WAVEFORM_TRANSFORM_FINAL = WAVEFORM_TRANSFORM_MINUS * a

                # Data Process
                WAVEFORM[k[0]:k[1]] = WAVEFORM_TRANSFORM_FINAL
                # IPython.display.Audio(data=WAVEFORM, rate=SR)

                sf.write(f'/Users/valleotb/Desktop/Valleotb/librispeech_processed/{z}_{k[0]}_{k[1]}.wav', WAVEFORM, SR, subtype="PCM_24")
                wr.writerow([f'{z}_{k[0]}_{k[1]}.wav',f'{k[0]}',f'{k[1]}'])
                print(f'complete{z}')

f.close()

[[  5632  25088]
 [ 25600  41472]
 [ 43520  44544]
 [ 46592 104960]
 [105472 105984]
 [111616 130560]
 [131072 157184]
 [161792 172544]
 [173056 194560]]
5632 25088
--
complete200001
25600 41472
--
complete200002
46592 104960
--
complete200003
111616 130560
--
complete200004
131072 157184
--
complete200005
161792 172544
--
complete200006
173056 194560
--
complete200007
[[ 6656 53760]
 [57344 71680]]
6656 53760
--
complete200008
57344 71680
--
complete200009
[[  5120  24064]
 [ 25600  55808]
 [ 56320  71168]
 [ 72704  80896]
 [ 81408  87040]
 [100352 112640]
 [114176 128000]
 [133632 180224]
 [180736 183808]
 [185856 204800]
 [206336 215040]]
5120 24064
--
complete200010
25600 55808
--
complete200011
56320 71168
--
complete200012
72704 80896
--
complete200013
81408 87040
--
complete200014
100352 112640
--
complete200015
114176 128000
--
complete200016
133632 180224
--
complete200017
180736 183808
--
complete200018
185856 204800
--
complete200019
206336 215040
--
complete200020
[[  4096 

RuntimeError: Error opening '/Users/valleotb/Desktop/Valleotb/librispeech_no_process/102621.flac': System error.