In [74]:
import os
import json
import pandas as pd
import torch
from torch.utils.data.dataloader import DataLoader

In [75]:
FILENAME_DIR = '/Users/valleotb/Desktop/Valleotb/sample_filename/metadata.csv'
ANNOTATION_DIR = '/Users/valleotb/Desktop/Valleotb/sample_metadata'
AUDIO_DIR = '/Users/valleotb/Desktop/Valleotb/sample_save'

In [76]:
filename_csv = pd.read_csv(FILENAME_DIR)
audio_path = os.path.join(AUDIO_DIR, filename_csv.iloc[0][0])
print(audio_path)

/Users/valleotb/Desktop/Valleotb/sample_save/200001_5632_25088.wav


In [80]:
annotation_path = os.path.join(ANNOTATION_DIR, filename_csv.iloc[0][1])
data_list = pd.read_json(annotation_path)
print(data_list['speech_segments'][0]['start_time'])
start_time_list = []
for idx in range(len(data_list)):
    start_time_list.append(data_list['speech_segments'][idx]['start_time'])

print(start_time_list)

5125
[5125, 6150, 7175, 8200, 9225, 10250, 11275, 12300, 13325, 14350, 15375, 16400, 17425, 18450, 19475, 20500, 21525, 22550, 23575]


In [112]:
start_time_list = []


for i in range(len(filename_csv)):
    annotation_path = os.path.join(ANNOTATION_DIR, filename_csv.iloc[i][1])
    data_list = pd.read_json(annotation_path)
    list2 = []
    list3 = {}
    for idx in range(len(data_list)):

        list2.append(data_list['speech_segments'][idx]['start_time'])
        list3["time"] = torch.tensor(list2, dtype=torch.float32)
        list3["label"] = torch.tensor(1, dtype=torch.float32)

    # labels = [1 for j in range(len(list2))]
    # dataset = list(zip(list2,labels))
    start_time_list.append(list3)
print(start_time_list)

[{'time': tensor([ 5125.,  6150.,  7175.,  8200.,  9225., 10250., 11275., 12300., 13325.,
        14350., 15375., 16400., 17425., 18450., 19475., 20500., 21525., 22550.,
        23575.]), 'label': tensor(1.)}, {'time': tensor([24600., 25625., 26650., 27675., 28700., 29725., 30750., 31775., 32800.,
        33825., 34850., 35875., 36900., 37925., 38950., 39975.]), 'label': tensor(1.)}, {'time': tensor([ 46125.,  47150.,  48175.,  49200.,  50225.,  51250.,  52275.,  53300.,
         54325.,  55350.,  56375.,  57400.,  58425.,  59450.,  60475.,  61500.,
         62525.,  63550.,  64575.,  65600.,  66625.,  67650.,  68675.,  69700.,
         70725.,  71750.,  72775.,  73800.,  74825.,  75850.,  76875.,  77900.,
         78925.,  79950.,  80975.,  82000.,  83025.,  84050.,  85075.,  86100.,
         87125.,  88150.,  89175.,  90200.,  91225.,  92250.,  93275.,  94300.,
         95325.,  96350.,  97375.,  98400.,  99425., 100450., 101475., 102500.,
        103525.]), 'label': tensor(1.)}, {'t

In [113]:
dataloader = torch.utils.data.DataLoader(start_time_list, batch_size=1)

for data in dataloader:
    print(data['time'])

tensor([[ 5125.,  6150.,  7175.,  8200.,  9225., 10250., 11275., 12300., 13325.,
         14350., 15375., 16400., 17425., 18450., 19475., 20500., 21525., 22550.,
         23575.]])
tensor([[24600., 25625., 26650., 27675., 28700., 29725., 30750., 31775., 32800.,
         33825., 34850., 35875., 36900., 37925., 38950., 39975.]])
tensor([[ 46125.,  47150.,  48175.,  49200.,  50225.,  51250.,  52275.,  53300.,
          54325.,  55350.,  56375.,  57400.,  58425.,  59450.,  60475.,  61500.,
          62525.,  63550.,  64575.,  65600.,  66625.,  67650.,  68675.,  69700.,
          70725.,  71750.,  72775.,  73800.,  74825.,  75850.,  76875.,  77900.,
          78925.,  79950.,  80975.,  82000.,  83025.,  84050.,  85075.,  86100.,
          87125.,  88150.,  89175.,  90200.,  91225.,  92250.,  93275.,  94300.,
          95325.,  96350.,  97375.,  98400.,  99425., 100450., 101475., 102500.,
         103525.]])
tensor([[110700., 111725., 112750., 113775., 114800., 115825., 116850., 117875.,
   

In [124]:
def make_batch(samples) :
    inputs = [sample['time'] for sample in samples]
    labels = [sample['label'] for sample in samples]
    padded_inputs = torch.nn.utils.rnn.pad_sequence(inputs, batch_first=True)
    return {'input': padded_inputs.contiguous(),
            'label': torch.stack(labels).contiguous()}

sampler = torch.utils.data.RandomSampler(start_time_list)
batch_sampler = torch.utils.data.BatchSampler(sampler,len(start_time_list),False)
dataloader = torch.utils.data.DataLoader(start_time_list,batch_sampler=batch_sampler, collate_fn=make_batch)
for data in dataloader:
    print(data['input'], data['label'])

tensor([[ 46125.,  47150.,  48175.,  ..., 101475., 102500., 103525.],
        [130175., 131200., 132225.,  ...,      0.,      0.,      0.],
        [172200., 173225., 174250.,  ...,      0.,      0.,      0.],
        ...,
        [ 24600.,  25625.,  26650.,  ...,      0.,      0.,      0.],
        [ 99425., 100450., 101475.,  ...,      0.,      0.,      0.],
        [185525., 186550., 187575.,  ...,      0.,      0.,      0.]]) tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.])


In [62]:
point_sampler = RandomSampler(dataset)
batch_sampler = BatchSampler(point_sampler, 1024, False)
dataloader = torch.utils.data.DataLoader(dataset, batch_sampler=batch_sampler)

for data in dataloader:
    print(data[0], data[1])

tensor([ 5125, 16400,  8200, 14350, 11275,  7175, 12300, 19475, 20500, 22550,
        18450,  9225, 17425, 15375, 13325,  6150, 21525, 23575, 10250]) tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [70]:
from torch.utils.data import Dataset

class VarMapDataset(Dataset):
    def __len__(self):
        return 10

    def __getitem__(self, idx):
        return {"input":torch.tensor([idx] * (idx+1),
                                     dtype=torch.float32),
                "label": torch.tensor(idx,
                                      dtype=torch.float32)}

var_map_dataset = VarMapDataset()

In [71]:
dataloader = torch.utils.data.DataLoader(var_map_dataset)
for data in dataloader:
    print(data['input'])

tensor([[0.]])
tensor([[1., 1.]])
tensor([[2., 2., 2.]])
tensor([[3., 3., 3., 3.]])
tensor([[4., 4., 4., 4., 4.]])
tensor([[5., 5., 5., 5., 5., 5.]])
tensor([[6., 6., 6., 6., 6., 6., 6.]])
tensor([[7., 7., 7., 7., 7., 7., 7., 7.]])
tensor([[8., 8., 8., 8., 8., 8., 8., 8., 8.]])
tensor([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])


In [72]:
def make_batch(samples):
    inputs = [sample['input'] for sample in samples]
    labels = [sample['label'] for sample in samples]
    padded_inputs = torch.nn.utils.rnn.pad_sequence(inputs, batch_first=True)
    return {'input': padded_inputs.contiguous(),
            'label': torch.stack(labels).contiguous()}

dataloader = torch.utils.data.DataLoader(var_map_dataset,
                                         batch_size=3,
                                         collate_fn=make_batch)
for data in dataloader:
    print(data['input'], data['label'])

tensor([[0., 0., 0.],
        [1., 1., 0.],
        [2., 2., 2.]]) tensor([0., 1., 2.])
tensor([[3., 3., 3., 3., 0., 0.],
        [4., 4., 4., 4., 4., 0.],
        [5., 5., 5., 5., 5., 5.]]) tensor([3., 4., 5.])
tensor([[6., 6., 6., 6., 6., 6., 6., 0., 0.],
        [7., 7., 7., 7., 7., 7., 7., 7., 0.],
        [8., 8., 8., 8., 8., 8., 8., 8., 8.]]) tensor([6., 7., 8.])
tensor([[9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]]) tensor([9.])


In [73]:
sampler = RandomSampler(var_map_dataset)
dataloader = torch.utils.data.DataLoader(var_map_dataset,
                                         batch_size=3,
                                         sampler=sampler,
                                         collate_fn=make_batch)
for data in dataloader:
    print(data['input'], data['label'])

tensor([[7., 7., 7., 7., 7., 7., 7., 7.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [4., 4., 4., 4., 4., 0., 0., 0.]]) tensor([7., 0., 4.])
tensor([[1., 1., 0., 0., 0., 0.],
        [5., 5., 5., 5., 5., 5.],
        [2., 2., 2., 0., 0., 0.]]) tensor([1., 5., 2.])
tensor([[8., 8., 8., 8., 8., 8., 8., 8., 8., 0.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
        [6., 6., 6., 6., 6., 6., 6., 0., 0., 0.]]) tensor([8., 9., 6.])
tensor([[3., 3., 3., 3.]]) tensor([3.])


In [149]:
AUDIO_DIR = '/Users/valleotb/Desktop/Valleotb/sample_save'
FILENAME_DIR = '/Users/valleotb/Desktop/Valleotb/sample_filename/metadata.csv'

filename_csv = pd.read_csv(FILENAME_DIR)
# print(filename_csv['audio_file'][1])
print(len(filename_csv))

path = os.path.join(filename_csv['audio_file'][0])
print(path)
print(path[-5])
'''
files = os.listdir(path)
for i in files :
    print(i)
'''

483
/Users/valleotb/Desktop/Valleotb/sample_save/200000_0_0.wav
0


'\nfiles = os.listdir(path)\nfor i in files :\n    print(i)\n'

In [ ]:
for inputs, targets in data_loader:
    inputs, targets = inputs, targets